### ISSUE TITLE
Odom after 

### ISSUE THREAD

**Issue by terencenwz** [bhctsntrk/mantis_ddqn_navigation#3]
@bhctsntrk Hi, I'm not raising any issue but I just a small doubt that I would like to ask you. I am currently running a similar project for the jackal robot on gazebo. However for my case, the odom topic does not seem to reset after calling '/gazebo/set_model_state', i.e. it is still stuck at its previous pose. May I ask if you had encountered this before and how did you solve it? Thank you

**Comment by bhctsntrk** [comment]
Jackal bot design may be different. Try to set Odom manually https://answers.ros.org/question/235228/how-is-the-orientation-of-frame-odom-initialized/

**Comment by terencenwz** [comment]
> Jackal bot design may be different. Try to set Odom manually https://answers.ros.org/question/235228/how-is-the-orientation-of-frame-odom-initialized/

Thank you, I will try it!
